-- GWS Enterprise 사용자 데이터 삽입
-- 총 87명

INSERT INTO gws_assignments (email, is_active) VALUES
  ('kyoungshin@treenod.com', true),
  ('yujeong@treenod.com', true),
  ('communication@treenod.com', true),
  ('minbeom@treenod.com', true),
  ('gw@treenod.com', true),
  ('lt-totp@treenod.com', true),
  ('ga@treenod.com', true),
  ('support@treenod.com', true),
  ('hr@treenod.com', true),
  ('help@treenod.com', true),
  ('scan@treenod.com', true),
  ('mookwan@treenod.com', true),
  ('sangwan@treenod.com', true),
  ('kakao@treenod.com', true),
  ('sohyun@treenod.com', true),
  ('qa03@treenod.com', true),
  ('hr_info@treenod.com', true),
  ('jueun@treenod.com', true),
  ('globalgames@treenod.com', true),
  ('pokotube@treenod.com', true),
  ('treenod_mkt@treenod.com', true),
  ('appstore@treenod.com', true),
  ('jinmyung@treenod.com', true),
  ('review@treenod.com', true),
  ('hosung@treenod.com', true),
  ('marketing@treenod.com', true),
  ('jihun3@treenod.com', true),
  ('junin@treenod.com', true),
  ('pokopang_billing01@treenod.com', true),
  ('byounggu@treenod.com', true),
  ('jaehoon@treenod.com', true),
  ('cs_agent01@treenod.com', true),
  ('bokyoung@treenod.com', true),
  ('junghyun@treenod.com', true),
  ('jiwon04@treenod.com', true),
  ('yeonghyeon@treenod.com', true),
  ('jiheon@treenod.com', true),
  ('billingqa@treenod.com', true),
  ('hyeon@treenod.com', true),
  ('webpromotion@treenod.com', true),
  ('sujin@treenod.com', true),
  ('kyunghee@treenod.com', true),
  ('youngji02@treenod.com', true),
  ('recruit@treenod.com', true),
  ('jaejung@treenod.com', true),
  ('notice@treenod.com', true),
  ('yungyeong@treenod.com', true),
  ('hyeji2@treenod.com', true),
  ('kihyun02@treenod.com', true),
  ('sina@treenod.com', true),
  ('pokopang_billing02@treenod.com', true),
  ('eunchan@treenod.com', true),
  ('minyong@treenod.com', true),
  ('moonho@treenod.com', true),
  ('qa02@treenod.com', true),
  ('yeji@treenod.com', true),
  ('master@treenod.com', true),
  ('casual_ustest@treenod.com', true),
  ('jaekoo@treenod.com', true),
  ('admin@treenod.com', true),
  ('seongyeon@treenod.com', true),
  ('link@treenod.com', true),
  ('lt-dev@treenod.com', true),
  ('casual_cs@treenod.com', true),
  ('eunji04@treenod.com', true),
  ('woosik@treenod.com', true),
  ('sanghoon@treenod.com', true),
  ('ldap-readonly@treenod.com', true),
  ('kyounghwa03@treenod.com', true),
  ('ahram@treenod.com', true),
  ('hyeonjin2@treenod.com', true),
  ('tech@treenod.com', true),
  ('financeguide@treenod.com', true),
  ('poko_media@treenod.com', true),
  ('ikhoon@treenod.com', true),
  ('jihoon@treenod.com', true),
  ('youngsoo@treenod.com', true),
  ('joonsoo@treenod.com', true),
  ('won02@treenod.com', true),
  ('youngju@treenod.com', true),
  ('gunhyoung@treenod.com', true),
  ('trlegal@treenod.com', true),
  ('qa01@treenod.com', true),
  ('ingyu@treenod.com', true),
  ('contact@treenod.com', true),
  ('heekyung@treenod.com', true),
  ('seungam@treenod.com', true)
ON CONFLICT (email) DO NOTHING;

-- 소프트웨어 라이선스 할당 데이터 삽입
-- 총 59건

INSERT INTO software_assignments (user_email, category, product, is_all_products_pack, is_active) VALUES
  ('sujin02@treenod.com', 'Jetbrain', 'Rider - Commercial annual subscription', false, true),
  ('jeongwon@treenod.com', 'Jetbrain', 'Rider - Commercial annual subscription', false, true),
  ('saerom@treenod.com', 'Jetbrain', 'Rider - Commercial annual subscription', false, true),
  ('jinmyung@treenod.com', 'Jetbrain', 'Rider - Commercial annual subscription', false, true),
  ('jaewoo@treenod.com', 'Jetbrain', 'Rider - Commercial annual subscription', false, true),
  ('hayoung@treenod.com', 'Jetbrain', 'Rider - Commercial annual subscription', false, true),
  ('jeongwoo@treenod.com', 'Jetbrain', 'Rider - Commercial annual subscription', false, true),
  ('jeonghyeon@treenod.com', 'Jetbrain', 'Rider - Commercial annual subscription', false, true),
  ('youngsoo@treenod.com', 'Jetbrain', 'Rider - Commercial annual subscription', false, true),
  ('misung@treenod.com', 'Jetbrain', 'Rider - Commercial annual subscription', false, true),
  ('gukcheon@treenod.com', 'Jetbrain', 'Rider - Commercial annual subscription', false, true),
  ('ingyo@treenod.com', 'Jetbrain', 'Rider - Commercial annual subscription', false, true),
  ('minkyung@treenod.com', 'Jetbrain', 'DataGrip - Commercial annual subscription', false, true),
  ('indeok@treenod.com', 'Jetbrain', 'DataGrip - Commercial annual subscription', false, true),
  ('seongwoo@treenod.com', 'Jetbrain', 'IntelliJ IDEA Ultimate - Commercial annual subscription', false, true),
  ('miyeon@treenod.com', 'Jetbrain', 'IntelliJ IDEA Ultimate - Commercial annual subscription', false, true),
  ('hyewon04@treenod.com', 'Jetbrain', 'IntelliJ IDEA Ultimate - Commercial annual subscription', false, true),
  ('taekwon@treenod.com', 'Jetbrain', 'IntelliJ IDEA Ultimate - Commercial annual subscription', false, true),
  ('sangwan@treenod.com', 'Jetbrain', 'IntelliJ IDEA Ultimate - Commercial annual subscription', false, true),
  ('aram02@treenod.com', 'Jetbrain', 'All Products Pack - Commercial annual subscription', true, true),
  ('dongwan@treenod.com', 'Jetbrain', 'All Products Pack - Commercial annual subscription', true, true),
  ('sungwoo@treenod.com', 'Jetbrain', 'All Products Pack - Commercial annual subscription', true, true),
  ('hyeongjin@treenod.com', 'Jetbrain', 'All Products Pack - Commercial annual subscription', true, true),
  ('myeongseon@treenod.com', 'Jetbrain', 'All Products Pack - Commercial annual subscription', true, true),
  ('seolhui@treenod.com', 'Jetbrain', 'All Products Pack - Commercial annual subscription', true, true),
  ('minseok02@treenod.com', 'Jetbrain', 'All Products Pack - Commercial annual subscription', true, true),
  ('yui@treenod.com', 'Jetbrain', 'All Products Pack - Commercial annual subscription', true, true),
  ('hojin@treenod.com', 'Jetbrain', 'All Products Pack - Commercial annual subscription', true, true),
  ('gukcheon@treenod.com', 'Jetbrain', 'All Products Pack - Commercial annual subscription', true, true),
  ('hosung@treenod.com', 'Jetbrain', 'All Products Pack - Commercial annual subscription', true, true),
  ('songyi@treenod.com', 'Jetbrain', 'All Products Pack - Commercial annual subscription', true, true),
  ('jeonghyeon@treenod.com', 'Jetbrain', 'All Products Pack - Commercial annual subscription', true, true),
  ('gyunchae@treenod.com', 'Autodesk', 'Maya', false, true),
  ('seungsu02@treenod.com', 'Autodesk', 'Maya', false, true),
  ('yonguk@treenod.com', 'Autodesk', 'Maya', false, true),
  ('mira@treenod.com', 'Autodesk', 'Maya', false, true),
  ('sunyoung02@treenod.com', 'Autodesk', 'Maya', false, true),
  ('jiseon@treenod.com', 'Autodesk', '3ds max', false, true),
  ('hyojin@treenod.com', 'Autodesk', '3ds max', false, true),
  ('jaegyu@treenod.com', 'Autodesk', '3ds max', false, true),
  ('taesoo@treenod.com', 'Autodesk', '3ds max', false, true),
  ('boram02@treenod.com', 'Shutterstock', 'Shutterstock', false, true),
  ('yeojin@treenod.com', 'Shutterstock', 'Shutterstock', false, true),
  ('miae@treenod.com', 'Shutterstock', 'Shutterstock', false, true),
  ('eunjung@treenod.com', 'Shutterstock', 'Shutterstock', false, true),
  ('sooyeon@treenod.com', 'spine', 'spine', false, true),
  ('gayong@treenod.com', 'spine', 'spine', false, true),
  ('myeongkyo@treenod.com', 'spine', 'spine', false, true),
  ('minji06@treenod.com', 'spine', 'spine', false, true),
  ('haesue@treenod.com', 'spine', 'spine', false, true),
  ('hyojin@treenod.com', 'spine', 'spine', false, true),
  ('taeyong@treenod.com', 'spine', 'spine', false, true),
  ('munguk@treenod.com', 'spine', 'spine', false, true),
  ('dongwook@treenod.com', 'spine', 'spine', false, true),
  ('jinseong@treenod.com', 'spine', 'spine', false, true),
  ('boram02@treenod.com', 'spine', 'spine', false, true),
  ('minjang@treenod.com', 'spine', 'spine', false, true),
  ('myeongkyo@treenod.com', 'spine', 'spine', false, true),
  ('jinseon@treenod.com', 'spine', 'spine', false, true);

-- 통계:
-- GWS Enterprise: 87명
-- 소프트웨어 할당: 59건
--   Jetbrain: 32건
--   Autodesk: 9건
--   Shutterstock: 4건
--   spine: 14건
-- All Products Pack: 13건
